name: Workflow of utn-evaluator kernel

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Testing App
      run: |
        cd CodeEvaluator/src && python -m unittest discover tests     
  
